# Generated by Django 5.1.6 on 2025-02-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='landing_page_url',
            field=models.CharField(max_length=300),
        ),
    ]
